from __future__ import annotations

from collections.abc import AsyncIterable, Iterable
from typing import Protocol, runtime_checkable


@runtime_checkable
class SyncRedisClientProto(Protocol):
    """Protocol for the subset of redis-py sync client we use."""

    # Basic ops
    def get(self, name: str) -> bytes | str | None: ...

    def set(self, name: str, value: object, *, ex: int | None = None, px: int | None = None) -> bool: ...

    def delete(self, name: str) -> int: ...

    def exists(self, name: str) -> int | bool: ...

    # TTL ops
    def ttl(self, name: str) -> int: ...

    def expire(self, name: str, seconds: int) -> int: ...

    def expireat(self, name: str, timestamp: int) -> int: ...

    def pexpire(self, name: str, ms: int) -> int: ...

    def persist(self, name: str) -> int: ...

    # Counters / scripting
    def incrby(self, name: str, delta: int) -> int: ...

    def eval(self, script: str, numkeys: int, *keys_and_args: object) -> object: ...

    # Sets / scan / bulk
    def sadd(self, name: str, *values: object) -> int: ...

    def smembers(self, name: str) -> set: ...  # noqa: PYI041

    def scan_iter(self, match: str, count: int | None = None) -> Iterable[bytes | str]: ...

    def delete_many(self, *names: str) -> int: ...

    def flushdb(self) -> None: ...

    # Pub/Sub and health
    def publish(self, channel: str, data: str) -> int: ...

    def pubsub(self) -> object: ...

    def ping(self) -> bool: ...

    def close(self) -> None: ...


@runtime_checkable
class AsyncRedisClientProto(Protocol):
    """Protocol for the subset of redis.asyncio client we use."""

    # Basic ops
    async def get(self, name: str) -> bytes | str | None: ...

    async def set(self, name: str, value: object, *, ex: int | None = None, px: int | None = None) -> bool: ...

    async def delete(self, name: str) -> int: ...

    async def exists(self, name: str) -> int | bool: ...

    # TTL ops
    async def ttl(self, name: str) -> int: ...

    async def expire(self, name: str, seconds: int) -> int: ...

    async def expireat(self, name: str, timestamp: int) -> int: ...

    async def pexpire(self, name: str, ms: int) -> int: ...

    async def persist(self, name: str) -> int: ...

    # Counters / scripting
    async def incrby(self, name: str, delta: int) -> int: ...

    async def eval(self, script: str, numkeys: int, *keys_and_args: object) -> object: ...

    # Sets / scan / bulk
    async def sadd(self, name: str, *values: object) -> int: ...

    async def smembers(self, name: str) -> set: ...  # noqa: PYI041

    def scan_iter(self, match: str) -> AsyncIterable[bytes | str]: ...

    async def delete_many(self, *names: str) -> int: ...

    async def flushdb(self) -> None: ...

    # Pub/Sub and health
    async def publish(self, channel: str, data: str) -> int: ...

    def pubsub(self) -> object: ...

    async def ping(self) -> bool: ...

    async def close(self) -> None: ...


__all__ = ["SyncRedisClientProto", "AsyncRedisClientProto"]
